### ISSUE TITLE
Max clients

### ISSUE THREAD

**Issue by auchri** [stilliard/docker-pure-ftpd#107]
Hi,

I'm using docker-compose:
```
  ftpd_server:
    image: stilliard/pure-ftpd:latest
    hostname: ftpd_server
    restart: unless-stopped
    environment:
      PUBLICHOST: "xxx"
      ADDED_FLAGS: "--tls 2 -C 10 -c 10"
      TLS_CN: "xxx"
      TLS_ORG: "xxx"
      TLS_C: "xxx"
    volumes:
      - ftp_data:/home/ftpusers
      - ftp_passwd:/etc/pure-ftpd/passwd
      - ftp_tls:/etc/ssl/private/
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
```

in the logs I can see that the max client parameter is set to 10:
```
Starting Pure-FTPd:
  pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P xxx --tls 2 -C 10 -c 10  -p 30000:30009
```

However when connecting I get the following error:
`421 5 users (the maximum) are already logged in, sorry`
