### ISSUE TITLE
Exit code 1 while running with TLS1.2

### ISSUE THREAD

**Issue by ardesai** [stilliard/docker-pure-ftpd#110]
When I try to run the image with following command:

`sudo docker  run --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" -e FTP_USER_NAME=bob -e FTP_USER_PASS=password -e FTP_USER_HOME=/home/bob  -e "ADDED_FLAGS=--tls=2" -v /tmp/storage/pure-ftpd.pem:/etc/ssl/private/pure-ftpd.pem:ro stilliard/pure-ftpd:hardened`

It is exiting with error code 1. It only works when I run this in interactive mode with argument '-it' which allows me enter the password for the ssl certificate 'pure-ftpd.pem'.

I am getting same error with docker compose file as well:
```
version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: ftpd_server
    ports:
    - "21:21"
    - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
    - "/tmp/storage/pure-ftpd.pem:/etc/ssl/private/pure-ftpd.pem:ro"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: bob
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/bob
      ADDED_FLAGS: "--tls=2"
    restart: always
```

Logs:
```
Creating ftpd_server ... done
Attaching to ftpd_server
ftpd_server    | Creating user...
ftpd_server    | Password: 
ftpd_server    | Enter it again: 
ftpd_server    |  root user give /home/bob directory ftpuser owner
ftpd_server    | Setting default port range to: 30000:30009
ftpd_server    | Setting default max clients to: 5
ftpd_server    | Setting default max connections per ip to: 5
ftpd_server    | Starting Pure-FTPd:
ftpd_server    |   pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -s -A -j -Z -H -4 -E -R -G -X -x --tls=2  -p 30000:30009 -c 5 -C 5
ftpd_server    | Enter PEM pass phrase:
ftpd_server exited with code 1
```
