### ISSUE TITLE
Extending docker-pure-ftp

### ISSUE THREAD

**Issue by lrkwz** [stilliard/docker-pure-ftpd#12]
Hello I've extended your image with a simple Dockerfile which adds a prebuild pdb

```
FROM stilliard/pure-ftpd
VOLUME /home/ftpusers/someone
ADD pureftpd.pdb /etc/pure-ftpd/
```

When I run this new container in a docker-compose port 21 is closed. The same container uses a mysql image where ports are opened on the host in the same way.
What am I doing wrong?

This is my docker-compose

```
fidelio-application:
  build: code
  volumes:
    - ../../../../data:/home/ftpusers/someone
  tty: true
fidelio-db:
  image: mysql
  ports:
    - 3306:3306
  volumes_from:
    - fidelio-application
ftpserver:
  build: ftp
  container_name: ftpserver
  ports:
    - 21:21
    - 30000-30009:30000-30009
  environment:
    PUBLICHOST: localhost
  volumes_from:
    - fidelio-application
```

BTW if i run the image directly with ```docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "PUBLICHOST=localhost" stilliard/pure-ftpd``` the cointainer operates correctly.
