### ISSUE TITLE
is the password path right?

### ISSUE THREAD

**Issue by champ-isaac** [stilliard/docker-pure-ftpd#120]
I created the new account and want to check the account by using
`pure-pw show username`

However the console display that
```
Unable to open the passwd file: No such file or directory
Unable to fetch info about user [usrname] in file [/etc/pure-ftpd/pureftpd.passwd]
```

And the real file is in `/etc/pure-ftpd/passwd/pureftpd.passwd`~~

At meantime while using ftp client to login, the console display that
```
Command:	USER username
Response: 	331 User username OK. Password required
Command:	PASS ************
Response: 	530 Login authentication failed
```

Is that it can not find the password file?

I'm using `docker-compose` to create ftp container, any suggestions to fix that?

**Comment by champ-isaac** [comment]
This is my docker-compose content,
```
portal_ftp:
    image: stilliard/pure-ftpd:hardened
    container_name: portal_ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./data/username:/home/username"
      - "./data/passwd:/etc/pur-ftpd/passwd"
    environment: 
      PUBLICHOST: "localhost"
      FTP_USER_NAME: "username"
      FTP_USER_PASS: "123456"
      FTP_USER_HOME: "/home/username"
      FTP_USER_UID: 9000
      FTP_USER_GID: 9000
    restart: always
```
