### ISSUE TITLE
Filezilla states that FTP connection is insecure

### ISSUE THREAD

**Issue by dovydasgulbinas** [stilliard/docker-pure-ftpd#121]
Hello could someone help me because I can't figure out why TLS connection is not established.  Even though the TLS certificates are generated successfully.

I tried:
ADDED_FLAGS="--tls"
ADDED_FLAGS="--tls=1"
ADDED_FLAGS="--tls=2"

None of the parameters seem to work, because all my connections are insecure according to FileZilla.  Only time I got TLS working was when [I generated certs manually.](https://github.com/stilliard/docker-pure-ftpd#tls)

```yaml
version: "3.3"

volumes:
  ftpd_user_vol:
  ftpd_passwd_vol:
  ftpd_ssl_cert_vol:

services:
  ftpd:
    environment:
      - PUBLICHOST
      - ADDED_FLAGS="--tls"
      - TLS_CN=Cool Corp FTP
      - TLS_ORG=Cool Corp
      - TLS_C=DK
      - FTP_USER_NAME
      - FTP_USER_PASS
      - FTP_USER_HOME 
    image: stilliard/pure-ftpd:hardened
    # command: /run.sh -c 30 -C 10 -l -E -j -R -P ${PUBLICHOST}
    volumes:
      - ftpd_user_vol:/home/ftpusers
      - ftpd_passwd_vol:/etc/pure-ftpd/passwd
      - ftpd_ssl_cert_vol:/etc/ssl/private
    ports:
      - ${FTPD_PORT}:21
      - 30000-30009:30000-30009
```
Thanks!

**Comment by stilliard** [comment]
Hi @dovydasgulbinas 
I believe the Common Name (TLS_CN) part needs to be a domain name, e.g. example.com
Could you try with this? 
Thanks

**Comment by dovydasgulbinas** [comment]
> Hi @dovydasgulbinas
> I believe the Common Name (TLS_CN) part needs to be a domain name, e.g. example.com
> Could you try with this?
> Thanks


Nope it did not help, but I have noticed one issue:

> 139703273943104:error:0D07A097:asn1 encoding routines:ASN1_mbstring_ncopy:string too long:../crypto/asn1/a_mbstr.c:109:maxsize=2

 [see full log here](https://pastebin.com/AuzQtVb3)


```yaml
version: "3.3"

volumes:
  ftpd_user_vol:
  ftpd_passwd_vol:
  ftpd_ssl_cert_vol:

services:
  ftpd:
    environment:
      - PUBLICHOST
      - ADDED_FLAGS="--tls"
      - TLS_CN=example.com
      - TLS_ORG=org
      - TLS_C=ccc
      # - FTP_USER_NAME
      # - FTP_USER_PASS
      # - FTP_USER_HOME 
    image: stilliard/pure-ftpd:hardened
    # command: /run.sh -c 30 -C 10 -l -E -j -R -P ${PUBLICHOST}
    volumes:
      - ftpd_user_vol:/home/ftpusers
      - ftpd_passwd_vol:/etc/pure-ftpd/passwd
      - ftpd_ssl_cert_vol:/etc/ssl/private
    ports:
      - ${FTPD_PORT}:21
      - 30000-30009:30000-30009
```
