### ISSUE TITLE
Unable to open [/etc/pure-ftpd/pureftpd.conf]: No such file or directory

### ISSUE THREAD

**Issue by aguerram** [stilliard/docker-pure-ftpd#131]
Hey there, I have to issue regrading using this image in docker it shows me this error : 
`Unable to open [/etc/pure-ftpd/pureftpd.conf]: No such file or directory`
This is my docker-compose code : 
```yaml
pure-ftpd:
    image: vimagick/pure-ftpd
    volumes:
      - '/CWS/ftp/data:/home/username'
      - '/CWS/ftp/passwd:/etc/pure-ftpd/passwd'
    ports:
      - "2100:21"
      # - "30000-30009:30000-30009"
    expose:
      - 21000
    privileged: true
    restart: always
    environment:
      - PUBLICHOST=localhost
      - FTP_USER_NAME=username
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/home/useit
```
I was trying to resolve this for 2h now, I hope you have a solution.
Thank you.
