### ISSUE TITLE
Passive port specification not respecting docker-compose

### ISSUE THREAD

**Issue by mikusHusbando** [stilliard/docker-pure-ftpd#133]
Hello. I am unable to open more than the default ports (30000-30009) by specifying it in the environment section of the docker-compose file.

```
version: '3.3'
services:
    pure-ftpd:
        image: stilliard/pure-ftpd
        container_name: ftpd_server
        ports:
            - "21:21"
            - "30000-30019:30000-30019"
        environment:
            - FTP_MAX_CLIENTS=20
            - FTP_USER_NAME=ftp-client
            - FTP_USER_PASS=supersecret
            - FTP_USER_HOME=/home/ftp-client
            - PUBLICHOST=192.168.1.82
        restart: always
```

this leads to the following:

```
root@hwmaster ~/D/scans-ftp # ❯❯❯ docker-compose up  --force-recreate                                                                ✘ 1
Recreating ftpd_server ... done
Attaching to ftpd_server
ftpd_server  | Creating user...
ftpd_server  | Password:
ftpd_server  | Enter it again: Error.
ftpd_server  | Check that [ftp-client] doesn't already exist,
ftpd_server  | and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written.
ftpd_server  |
ftpd_server  |  root user give /home/ftp-client directory ftpuser owner
ftpd_server  | Setting default port range to: 30000:30009
ftpd_server  | Setting default max clients to: 20
ftpd_server  | Setting default max connections per ip to: 5
ftpd_server  | Starting Pure-FTPd:
ftpd_server  |   pure-ftpd  -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P 192.168.1.82   -p 30000:30009 -c 20 -C 5
```
Any idea what I'm doing wrong? It seems to work when using docker run command:

``docker run -d --name ftpd_server-run -p 21:21 -p 30000-30019:30000-30019 -e FTP_MAX_CLIENTS=20 -e FTP_USER_NAME=ftp-client -e FTP_USER_PASS=noolookie! -e FTP_USER_HOME=/home/ftp-client -e "PUBLICHOST=192.168.1.82" stilliard/pure-ftpd`` 

Thank you for your time
