### ISSUE TITLE
Refused connection to FTP when using docker-compose instead of docker run

### ISSUE THREAD

**Issue by mr-bjerre** [stilliard/docker-pure-ftpd#137]
I have a `docker-compose.yml` looking like this

```yml
version: "3"
services: 
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    ports: 
      - "21"
      - "30000-30009"
    env_file: ftpd.env
```

with `ftpd.env` like this

```env
PUBLICHOST=localhost
ADDED_FLAGS=-d -d
```

But then I get this error

```bash
❯ ftp -p localhost 21
ftp: connect: Connection refuse
```

If I use `docker run` then I can connect just fine

```
docker run -d --name ftpd_server -p 21:21 -p 30000-30009:30000-30009 -e "ADDED_FLAGS=-d -d" stilliard/pure-ftpd:hardened
```

Any idea why that is?
