### ISSUE TITLE
PUBLICHOST configuration

### ISSUE THREAD

**Issue by Auggie321** [stilliard/docker-pure-ftpd#154]
Hi there,

use docker-compose.yml
```
version: '2'
services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./folder_on_disk/data:/home/username/"
      - "./folder_on_disk/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "172.16.200.128"
      FTP_USER_NAME: cassa
      FTP_USER_PASS: cassa123
      FTP_USER_HOME: /home/cassa
    restart: always
```

set docker-compose inner PUBLICHOST with host ip;

NAT Configuration in firewalld device (confirmed NAT configuration is correct)
104.243.xx.xx:221------->172.16.200.128:21

inner private network , you can access ftp with 172.16.200.128 21, 
you can't access 104.243.xx.xx:221;
i mean PUBLICHOST, is rigth to set 0.0.0.0 in Dockerfile or somewhere?
