### ISSUE TITLE
Bug: rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [stilliard/docker-pure-ftpd#157]
In /etc/rsyslog.conf need to comment out the following line

```
#module(load="imklog")   # provides kernel logging support
```

Work around
1. From the folder you have setup to run/manage pureftp container
2. docker cp $(docker ps -f name=pure-ftpd -q):/etc/rsyslog.conf ./
3. sed -i '/imklog/s/^/#/' rsyslog.conf
4. In your docker-compose.yml
```
version: '3'
services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes: # remember to replace /folder_on_disk/ with the path to where you want to store the files on the host machine
      - "/etc/localtime:/etc/localtime:ro"
      - "/ftp/rsyslog.conf:/etc/rsyslog.conf:ro"  ## <-- Add this line where /ftp is the folder you have setup for pureftp container data
      - "/ftp/var/log:/var/log"
      - "/ftp/data:/home/ftpusers/"
      - "/ftp/etc/ssl/private:/etc/ssl/private"
      - "/ftp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
#      FTP_USER_NAME: admin
#      FTP_USER_PASS: ...
#      FTP_USER_HOME: /home/admin
      ADDED_FLAGS: "-d -d --tls --tls=2"
    restart: always
```
