### ISSUE TITLE
`passwd` folder changed?

### ISSUE THREAD

**Issue by MarcelRobitaille** [stilliard/docker-pure-ftpd#184]
I followed the docs to create my setup and it has been running fine for months. Today, I rebooted my served (I did not update anything at all), and now it looks like pure ftp expects the password file to be in a different location. I was mounting the volume like `./ftp_passwd/:/etc/pure-ftpd/passwd`. However, I was unable to log in. I connected to the container and ran giving this result:
```
$ pure-pw show paperless
Unable to fetch info about user [paperless] in file [/etc/pure-ftpd/pureftpd.passwd]
```
It was looking for the password file in a different folder. I updated my volume to just `/etc/pure-ftpd/`. I also had to do `pure-pw mkdb`. Now, I am able to log in again.

What caused this change? Is this a bug or should the documentation be updated? Again, I did not update anything (not system packages or containers). I have pinned my version `stilliard/pure-ftpd:hardened-1.0.36`.

Relevant `docker-compose.yml`
```yml
  pure_ftpd:
    image: stilliard/pure-ftpd:hardened-1.0.36
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "./consume/data:/home/paperless/"
      - "./ftp_passwd:/etc/pure-ftpd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: paperless
      FTP_USER_PASS: <censored>
      FTP_USER_HOME: /home/paperless
    restart: unless-stopped

```
