### ISSUE TITLE
Can't access my FTP from outside

### ISSUE THREAD

**Issue by Richacinas** [stilliard/docker-pure-ftpd#186]
Hi there,

My docker pure-ftpd setup has been working for a long time, however, I don't know what happened that I'm not able to access it anymore.

Here is my config:

```
ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: <here the public IP of my server>
      FTP_USER_NAME: user
      FTP_USER_PASS: password
      FTP_USER_HOME: /var/www/html/my_website_folder
      FTP_USER_UID: 100
      FTP_USER_GID: 101
    volumes:
      - ./data/wordpress:/var/www/html/my_website_folder
      - ./data/ftp:/etc/ssl/privatec
    restart: unless-stopped
```

And here is the resulting opened ports on my Ubuntu server:

![OnPaste 20221003-123027](https://user-images.githubusercontent.com/7046504/193557434-27896b9b-8ed1-444e-a128-eec752b66065.png)

Of course, when I try to connect via ftp client using my credentials (user/password), it just gets a timeout.
