### ISSUE TITLE
usage of this container as a gitlab-ci service

### ISSUE THREAD

**Issue by fraxinas** [stilliard/docker-pure-ftpd#24]
Hi Andrew, i've been trying to use your container as a base for a gitlab continuous integration service. however, there are two issues,

1. during startup of the container, gitlab-ci runs into a timeout
```
Waiting for services to be up and running...

*** WARNING: Service runner-0f9980e5-project-711-concurrent-0-.....__...__ftpd_env probably didn't start properly.

service runner-0f9980e5-project-711-concurrent-0-.....__...__ftpd_env did timeout

*********
```
which is probably more of a gitlab-ci issue though. i need to find out what exactly it expects a service container to do to prevent the timeout. but this is just a minor issue and not a show-stopper.

2. the ftpd inside the service container can be reached but when trying to log in, i get this error:
`421 Illegal forced IP for passive connections`
i've set the PUBLICHOST matchingly to the adress that i actually connect to, according to
[https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#accessing-the-services](https://docs.gitlab.com/ce/ci/docker/using_docker_images.html#accessing-the-services)

do you have any suggestions?

**Comment by stilliard** [comment]
Hi Andreas, that sounds really interesting!
It may be a firewall issue on gitlab ci, I'm not currently able to test this with gitlab sorry. 
Does the container setup you have work fine locally?

**Comment by fraxinas** [comment]
I actually built a derived Dockerfile which has hardcorded ftp username and passwort and creates 2 ftp directories and sets different permissions on them. But yes, when manually running and starting that container locally, I can login and upload files :+1:

**Comment by fraxinas** [comment]
update: this seems to be an issue with pure-ftpd rather than docker. i've tried a container with proftp and that works as a gitlab-ci service without any problems

**Comment by stilliard** [comment]
Hi @fraxinas , Just following up, sorry it's so delayed. 
Did you ever find any reason why the container was being blocked?

**Comment by fraxinas** [comment]
no, sorry. i kept using proftpd instead

**Comment by stilliard** [comment]
No problem, I'm glad you got it working with proftpd though :).

**Comment by ellery** [comment]
Adding a comment here in case someone else runs into this issue using a ci platform and this docker image. The error we'd get was: 421 Illegal forced IP for passive connections

In your docker-compose file, you'll need to add a hostname parameter so an entry is created in /etc/hosts

```
ftpserver:
  image: stilliard/pure-ftpd:hardened
  ports:
    - "21:21"
    - "30000-30010:30000-30010"
  environment:
    ADDED_FLAGS: -d -d --tls 2
    TLS_CN: ftpserver
    TLS_ORG: demo
    TLS_C: US
    TLS_USE_DSAPRAM: "true"
    FTP_USER_NAME: testUser
    FTP_USER_PASS: testPassword
    PUBLICHOST: ftpserver
  hostname: ftpserver
```
