### ISSUE TITLE
Server sent passive reply with unroutable address. Using server address instead.

### ISSUE THREAD

**Issue by levonlee** [stilliard/docker-pure-ftpd#39]
The container has been fine until a few days ago FileZilla client had this error when using the Default as the Transfer mode. If I switched to Active, then the connection is fine.

Filezilla version 3.24.1

Here's my docker-compose.yml
```yml
version: '2'
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.3.0/24
        gateway: 172.16.3.1
services:
  newcomftp:
    build: .
    image: myftp:latest
    container_name: myftp
    environment:
      - PUBLICHOST=ftp.mydomain.com
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - /home/me/ftp:/home/ftpusers
      - /home/me/config/ftp/passwd:/etc/pure-ftpd/passwd
    networks:
      app_net:
        ipv4_address: 172.16.3.3
```

Dockerfile
```
FROM stilliard/pure-ftpd:hardened
CMD /run.sh -c 30 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R
```

`sudo docker-compose up -d --build`

It was working before without any changes. But now it doesn't work.
