### ISSUE TITLE
Allow ftpuser to change file/directory permissions

### ISSUE THREAD

**Issue by incr3m** [stilliard/docker-pure-ftpd#51]
I'm currently deploying wordpress app with docker. 

On my filezilla client, I am having troubles with following:

**1. I am not able to change permission of wp-content directory .** 

I get the following logs when I try to modify it using filezilla

     Command:	SITE CHMOD 777 wp-content
     Response:	550 Could not change perms on wp-content

Is there an option to allow user to change file permission. I created my ftpuser using the command      below:

     pure-pw useradd jim -f /etc/pure-ftpd/passwd/pureftpd.passwd -m -u ftpuser -d /home/ftpusers/jim

**2. Dot files are not showing. (I have enabled "Force showing hiddle files" in filezilla)**

This is my first time using pureftpd. Hope someone could help me. 
Thanks in advance :)

**Comment by stilliard** [comment]
Hey @incr3m  , 
Apologies for the very delayed reply, did you find the cause of this in the end?

**Comment by pensiero** [comment]
Same problem here, same error `550`, only when I try to rename a folder. While delete and creation of file/folders work perfectly.

**Comment by muhtarudinsiregar** [comment]
same problem here, got error 500 when rename file from Filezilla. i try in console, get the same error `550 Rename/move failure`.

**Comment by finex** [comment]
I'm also having a problem renaming files: I've created a virtual user with manual uid/gid from the host machine. Create/Upload/Delete files works fine, rename doesn't. I've also tried to set the value no on /etc/pure-ftpd/conf/NoRename but without any change.

**Comment by fbessadok** [comment]
Still having the issue ...

**Comment by danielmahon** [comment]
If you're using `image: stilliard/pure-ftpd:hardened` the `-G` (no renaming) flag is passed by default. To override you can override the `CMD` either in the dockerfile or the `command` option with docker-compose:

**docker-compose.yml**
```
command: /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P 'ftp.ctcs.app' -s -A -j -Z -H -4 -E -R -X -x
```

@stilliard sorry for the bringing this back to life, but this should probably be configurable as it's a common use-case right? Is there a security issue if the users are chrooted?

**Comment by stilliard** [comment]
Hi, looking back it seems this issue wasn't to do with renaming but after closed the issue seems to have become about this instead. 
I'd certainly be open to a new issue or pull request for disabling the norename protection by default though in the hardened branch.

**Comment by stilliard** [comment]
To help out, I'm proposing we switch the default tag #124 to latest instead of hadened. 
Let me know if you have any thoughts :+1:

**Comment by Dragane** [comment]
I have the :latest image and the files can be now renamed. The permissions on the other hand cannot be changed.

**Comment by stilliard** [comment]
Hi @Dragane & anyone else finding this old issue,

I believe we disable chmod by default, you'll need to enable it in the run command.

Please see the following for changing the run command: https://github.com/stilliard/docker-pure-ftpd#check-out-our-basic-example-workflow--our-slightly-more-advanced-workflow-with-tls--an-auto-created-user

Here's additional information on the default flags we use: https://github.com/stilliard/docker-pure-ftpd#our-default-pure-ftpd-options-explained

If there's any issues with this please open a new ticket, thank you.

**Comment by 8byr0** [comment]
Just came across this issue using docker compose, it might help if anyone also have this problem

According to the documentation, `-R` flag prevent non-root users to change permissions:
> Disallow users (even non-anonymous ones) usage of the CHMOD command. On hosting services, it may prevent newbies from doing mistakes, like setting bad permissions on their home directory. Only root can use CHMOD when this switch is enabled.

You need to change the RUN command like so (I just copied RUN from `Dockerfile` and removed the `-R` flag): 
```yml
version: '3.8'
services:
  ftp-server:
    image: stilliard/pure-ftpd:latest
    restart: unless-stopped
    # Here's the line added
    command: /run.sh -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -P localhost
    volumes:
      - "/my/bound/directory:/data"
    environment:
      FTP_USER_NAME: "${FTP_USER}"
      FTP_USER_PASS: "${FTP_PASSWORD}"
      FTP_USER_HOME: "/data"
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
```
