### ISSUE TITLE
pure-ftpd exited with code 252

### ISSUE THREAD

**Issue by vagafonov** [stilliard/docker-pure-ftpd#64]
Hello. 
I trying run docker-pure-ftpd from docker-compose. I using your config https://github.com/stilliard/docker-pure-ftpd/blob/master/docker-compose.yml

```
version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd:hardened
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/folder_on_disk/data:/home/ftpusers/"
      - "/folder_on_disk/passwd:/etc/pure-ftpd/passwd"
      - "/folder_on_disk/ssl:/etc/ssl/private/"
    environment:
      PUBLICHOST: "localhost"
      ADDED_FLAGS: "--tls=2"
    restart: always
```

When i try _docker-compose up_, i get:

```
$ docker-compose up
Recreating pure-ftpd ... 
Recreating pure-ftpd ... done
Attaching to pure-ftpd
pure-ftpd      | Starting Pure-FTPd:
pure-ftpd      |   pure-ftpd -c 5 -C 5 -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost -p 30000:30009 -s -A -j -Z -H -4 -E -R -G -X -x --tls=2 
pure-ftpd exited with code 252
```
ubuntu 18.04
Docker version 18.03.1-ce, build 9ee9f40
