### ISSUE TITLE
docker-compose and PASV

### ISSUE THREAD

**Issue by WouldYouKindly** [stilliard/docker-pure-ftpd#73]
Hello. 

I have pure-ftpd and my service in docker-compose. This service connects to FTP and everything is fine. However, I want to connect to FTP from my host machine too. I expose ports 21 and 31000-31009. I can connect and login from host machine, but cannot transfer any data: e.g. `mlsd` tells me that connection is refused.

IIUC, this happens because pure-ftpd is run with `-P {container_name}`. So when FTP client enters passive mode, it receives IP from Docker network which it doesn't know anything about.

Can anything be done to allow connecting from both Docker network and host machine? Am I missing something obvious?

My compose file:
```
ftp:
    image: stilliard/pure-ftpd
    environment:
      FTP_USER_NAME: user
      FTP_USER_PASS: password
      FTP_USER_HOME: /home/user
      FTP_PASSIVE_PORTS: "31000:31009"
      PUBLICHOST: ftp
    ports:
      - "10021:21"
      - "31000:31000"
      - "31001:31001"
      - "31002:31002"
      - "31003:31003"
      - "31004:31004"
      - "31005:31005"
      - "31006:31006"
      - "31007:31007"
      - "31008:31008"
      - "31009:31009"
    networks:
      - dev
```
