### ISSUE TITLE
Cannot connect due to 421 Unable to read the indexed puredb file (or old format detected) - Try pure-pw mkdb

### ISSUE THREAD

**Issue by JTT-JustTheTip** [stilliard/docker-pure-ftpd#91]
Every time i try to connect i get this error chucked out from FIleZilla 

`421 Unable to read the indexed puredb file (or old format detected) - Try pure-pw mkdb'

Not sure whats causing it, the container seems to be starting fine 

`Setting default port range to: 5250:5255
Setting default max clients to: 5
Setting default max connections per ip to: 5
Starting Pure-FTPd:
  pure-ftpd -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P localhost   -p 5250:5255 -c 5 -C 5`

My compose is as below - 

`MCFTP:
    image: stilliard/pure-ftpd
    container_name: MCFTP
    hostname: MCFTP
    restart: unless-stopped
    network_mode: le_bridge
    tty: true
    environment:
      FTP_PASSIVE_PORTS: 5250:5255
      FTP_USER_NAME: user
      FTP_USER_PASS: pass
    volumes:
    - /Docker_Configs/Minecraft_Stack/:/media
    ports:
    - 5250-5299:5250-5299
    - 5300:21`

**Comment by stilliard** [comment]
Hi @JTT-JustTheTip ,

I've not seen this error but have you tried setting the FTP_USER_HOME variable to a folder you'd like the user to have access to.

**Comment by Lone1567** [comment]
I am also running into this issue. I'm using: `ftp localhost` to connect and can't login with the credentials specified in my compose file. Do you have any other suggestions?

Thanks!

**Comment by stilliard** [comment]
Hi @Lone1567 
Did you try setting the FTP_USER_HOME as well?

Also, could you try connecting with `ftp -p localhost 21`

**Comment by marcoklein** [comment]
Same issue for me
'421 Unable to read the indexed puredb file (or old format detected) - Try pure-pw mkdb'
with FTP_USER_HOME set to '/'

**Comment by stilliard** [comment]
Hi @marcoklein 
Please could you try setting FTP_USER_HOME to '/home/yourusername'

**Comment by JayDi85** [comment]
Same 421 error.

Compose file (deleted all FTP_USER* and mounted commands -- but result was same):
![shot_181208_010203](https://user-images.githubusercontent.com/8344157/49672550-fb16c280-fa84-11e8-8b62-206eb0e6a80e.png)

Ftp result:
![shot_181208_005511](https://user-images.githubusercontent.com/8344157/49672567-0538c100-fa85-11e8-8b9d-2137e7a528f1.png)

**Comment by JayDi85** [comment]
It's can't create database and missing it:
![shot_181208_012518](https://user-images.githubusercontent.com/8344157/49673804-21d6f800-fa89-11e8-919b-f7fd6b13863d.png)

**Comment by stilliard** [comment]
Hi @JayDi85 ,
Interesting, could you please try creating a volume for the "/etc/pure-ftpd/passwd" folder as well?

**Comment by JayDi85** [comment]
Nope, it's not help.

I'm researched [run.sh](https://github.com/stilliard/docker-pure-ftpd/blob/master/run.sh) and found that code:
```
# Load in any existing db from volume store
if [ -e /etc/pure-ftpd/passwd/pureftpd.passwd ]
then
    pure-pw mkdb /etc/pure-ftpd/pureftpd.pdb -f "$PASSWD_FILE"
fi
```
If pureftpd.passwd is not exists then all script is failed. There are must be:
`touch /etc/pure-ftpd/passwd/pureftpd.passwd`
It's create empty file and db file by pure-pw too.

Well... Now `pureftpd.pdb` creates ok, but virtual user do not added on start. I don't known why. If I add manually then all works (ftp works too):
![shot_181208_034428](https://user-images.githubusercontent.com/8344157/49678096-b185a200-fa9b-11e8-8cbc-90f8a8251c4d.png)

**Comment by stilliard** [comment]
Hi @JayDi85 ,

I don't use docker compose much but I made a quick test & this worked fine for me:

```yml
version: '2'

services:
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: bob
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/bob
    volumes:
      - "/home/andrew/tmp/dpftpd/usr/data:/home/bob/"
      - "/home/andrew/tmp/dpftpd/usr/passwd:/etc/pure-ftpd/passwd"
```

Run with:
```bash
docker-compose up --build
```

& connected with:
```bash
ftp -p localhost 21
```

Not sure if this helps but maybe there's something in the above example that you don't have in your file? or anything to try?
