### ISSUE TITLE
Cannot connect externally through Docker Compose

### ISSUE THREAD

**Issue by mickgeek** [stilliard/docker-pure-ftpd#92]
Hello.

I have the next configuration:
```
  pure-ftpd:
    image: stilliard/pure-ftpd:hardened
    environment:
      - PUBLICHOST=xxx.xxx.xxx.xxx
      - FTP_USER_NAME=www-data
      - FTP_USER_PASS=<password>
      - FTP_USER_HOME=/home/www-data
    volumes:
      - pure-ftpd-data:/home
      - pure-ftpd-data:/etc/pure-ftpd/passwd
      - pure-ftpd-data:/etc/ssl/private
      - ../www:/srv/www
    ports:
      - 21:21/tcp
      - 30000-30009:30000-30009/tcp
```

I tried:
- increase maximum users
- increase the passive port range
- change the `PUBLICHOST` variable to the container host
- set `ADDED_FLAGS=--tls=0`

But it all not working to connect externally. What could be the problem?

**Comment by stilliard** [comment]
Hi @mickgeek , couple things to check:

Check with docker logs to see the container output. 
Also double check the publichost is the one you use to connect to with ftp.

If that doesn't help, could you paste me the error you're getting when connecting via fp

**Comment by stilliard** [comment]
Also worth checking if you have any firewall setup that needs the ports allowed through

**Comment by mickgeek** [comment]
`iptables` allow all connections for specified IPs, `PUBLICHOST` is correct. When I try connect from FileZilla, I get the next error:
```
Command: AUTH TLS
Error: Could not connect to server
```

`docker-compose exec pure-ftpd cat /var/log/syslog`:
```
Dec 10 14:32:51 771fe865cd97 pure-ftpd: (?@?) [ERROR] Unable to find the 'ftp' account
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [INFO] New connection from xxx.xxx.xxx.xxx
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] 220---------- Welcome to Pure-FTPd [privsep] [TLS] ----------
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] 220-You are user number 1 of 5 allowed.
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] 220-Local time is now 14:34. Server port: 21.
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] 220-This is a private system - No anonymous login
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [DEBUG] 220 You will be disconnected after 15 minutes of inactivity.
```

`docker-compose exec pure-ftpd tail -f /var/log/messages`:
```
Dec 10 14:34:12 771fe865cd97 pure-ftpd: (?@xxx.xxx.xxx.xxx) [INFO] New connection from xxx.xxx.xxx.xxx
```

**Comment by stilliard** [comment]
Thanks @mickgeek , could you also provide the output from `docker logs container-name`

**Comment by mickgeek** [comment]
After trying to connect:
```
Log enabled, see /var/log/messages
Creating user...
Password:
Error.
Check that [www-data] doesn't already exist,
and that [/etc/pure-ftpd/passwd/pureftpd.passwd.tmp] can be written.
Enter it again:
Setting default port range to: 30000:30009
Setting default max clients to: 5
Setting default max connections per ip to: 5
Starting Pure-FTPd:
  pure-ftpd -l puredb:/etc/pure-ftpd/pureftpd.pdb -E -j -R -P xxx.xxx.xxx.xxx -s -A -j -Z -H -4 -E -R -G -X -x --tls=0 -d -d  -p 30000:30009 -c 5 -C 5
```

**Comment by stilliard** [comment]
Thanks, it all looks the same as mine. (the error listed in the log is from when we try to recreate the user but it can be ignored). 

I've tested the following on a quick digital ocean server to make sure, all seems to be working:

```
version: '2'

services:
  pure-ftpd:
    image: stilliard/pure-ftpd:hardened
    environment:
      PUBLICHOST: xxx.xx.xxx.xxx
      FTP_USER_NAME: bob
      FTP_USER_PASS: mypass
      FTP_USER_HOME: /home/bob
    volumes:
      - "./usr/data:/home/bob/"
      - "./usr/passwd:/etc/pure-ftpd/passwd"
    ports:
      - 21:21/tcp
      - 30000-30009:30000-30009/tcp
```

But, i've just noticed in your log output you mentioned it said "Command: AUTH TLS" but you're not using TLS in your docker-compose. 

Could you try setting filezilla to connect with plain ftp (insecure)
